<?php

namespace Golpilolz\DbLogBundle\Repository;

/**
 * DbLogTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DbLogTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
