<?php

namespace Golpilolz\DbLogBundle\Repository;

/**
 * DbLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DbLogRepository extends \Doctrine\ORM\EntityRepository
{
}
